add option to generate primitive count trace in run script

diff --git a/run b/run
--- a/run
+++ b/run
@@ -31,6 +31,7 @@ TESTS=""          # empty to run all tests in tests directory
 ARITHMETIC=G      # generic (G) or specialized (S) arithmetic?
 VERSION_LIMIT=4   # version limit (0 to disable BBV)
 INLINING_LIMIT=0  # 0 for no function inlining
+PRIMITIVE_COUNT=0 # 0 for no primitive count
 
 # for gambit
 if test "$WIPGAMBITDIR" != "" ; then
@@ -66,6 +67,9 @@ while [ "$#" != "0" ]; do
         exit 1
       fi
       VERSION_LIMIT="$1"
+      ;;
+    -P) # primitive counts
+      PRIMITIVE_COUNT=1
       ;;
     -c|--clean) # clean
       rm -f tests/*/*.cfg tests/*/*.cfg.pdf tests/*/*.gvm tests/*/*.o* tests/*/*~ tests/*/*.bbv.dot tests/*/*.exe
@@ -145,7 +149,11 @@ for file in $FILES ; do
     gambit)
       DECL="(declare (version-limit $VERSION_LIMIT) (inlining-limit $INLINING_LIMIT) (standard-bindings) (extended-bindings) (not safe) (block)) (define-macro (%%%) (eval '(define arithmetic '$ARITHMETIC))) (%%%)"
       base="$filenoext.gambit.$INLINING_LIMIT$ARITHMETIC$VERSION_LIMIT"
-      $GAMBITCOMP -prelude "$DECL (##include \"$SCRIPT_DIR/gambit/bbv.scm\")" -postlude "(load \"$SCRIPT_DIR/gambit/main.scm\")" -keep-temp -gvm -cfg -exe -o $base.exe $file
+      if [ "$PRIMITIVE_COUNT" -eq "1" ]; then
+        PRIMITIVECOUNTTRACE=$base.trace
+        $GAMBITCOMP -prelude "$DECL (##include \"$SCRIPT_DIR/gambit/bbv.scm\")" -postlude "(run)" -gvm-interpret $file > $PRIMITIVECOUNTTRACE
+      fi
+      $GAMBITCOMP -prelude "$DECL (##include \"$SCRIPT_DIR/gambit/bbv.scm\")" -postlude "(load \"$SCRIPT_DIR/gambit/main.scm\")" -keep-temp -gvm -cfg $PRIMITIVE_COUNT_FLAG -exe -o $base.exe $file
       mv $filenoext.cfg $base.cfg
       run_dot $base.cfg
       CFGPDF=$base.cfg.pdf
@@ -154,6 +162,10 @@ for file in $FILES ; do
 
     bigloo)
       base="$filenoext.bigloo.$INLINING_LIMIT$ARITHMETIC$VERSION_LIMIT"
+      if [ "$PRIMITIVE_COUNT" -eq "1" ]; then
+        echo "ERROR: primitive count not supported for bigloo"
+        exit 1
+      fi
       PATH="$BIGLOODIR/bin:$PATH"
       (cd $SCRIPT_DIR/bigloo && \
        $BIGLOOCOMP -srfi arithmetic$ARITHMETIC bbv.bgl $file -saw -fsaw-bbv -o $base.exe && \
